client:
 tls:
  enabled: true

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 tcert:
  batch:
    size: 200

 logging:  
  level: INFO

 keystore:
  path: /tmp/msp

 cryptoconfig:
  path: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config"

 connection:
   timeout:
    peer:
     endorser: 3s
     eventHub: 3s
     eventReg: 3s
    orderer: 3s

# network provides a static definition of a Hyperledger Fabric network
 network:
  # list of ordering service nodes
  orderers:
   # orderer name
   orderer0:
    host: "orderer0.lenovo.com"
    #host: "101.89.63.173"
    port: 7050
    tls:
     # Certificate location absolute path
     certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/ordererOrganizations/lenovo.com/orderers/orderer2.lenovo.com/tls/ca.crt"
     # For testing only: overrides the virtual host name of the authority
     serverHostOverride: "orderer0.lenovo.com"

  # ap of member organizations forming the network
  organizations:
    # Org1 name
    peerorg1:
      # Membership Service Provider ID for this organization
      mspID: "Org1MSP"
      # CA config defines the fabric-ca instance that issues identities for this org
      ca:
       # TLS secured connections with the CA
       tlsEnabled: false
       # CA name
       name: "ca-org1"
       # CA URL. Note: https prefix required for TLS
       serverURL: "http://101.89.66.183:7054"
       # Configuration for mutual TLS with the CA
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/users/Admin@org1.lenovo.com/tls/ca.crt"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/users/Admin@org1.lenovo.com/tls/server.key"
         certfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/users/Admin@org1.lenovo.com/tls/server.crt"
      # Peers that are part of this organization
      peers:
       # Peer name
       peer0:
        host: "peer0.org1.lenovo.com"
        #host: "101.89.66.219"
        port: 7051
        eventHost: "peer0.org1.lenovo.com"
        #eventHost: "101.89.66.219"
        eventPort: 7053
        primary: false
        tls:
         # Certificate location absolute path
         #certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/peers/peer0.org1.lenovo.com/msp/cacerts/ca.org1.lenovo.com-cert.pem"
         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/peers/peer0.org1.lenovo.com/tls/ca.crt"
         serverHostOverride: "peer0.org1.lenovo.com"
#       peer1:
#        host: "101.89.66.183"
#        port: 8051
#        eventHost: "101.89.66.183"
#        eventPort: 8053
#        primary: false
#        tls:
#         # Certificate location absolute path
#         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org1.lenovo.com/peers/peer1.org1.lenovo.com/msp/cacerts/ca.org1.lenovo.com-cert.pem"
#         serverHostOverride: "peer1.org1.lenovo.com"
    # Org2
    peerorg2:
      mspID: "Org2MSP"
      ca:
       tlsEnabled: false
       name: "ca-org2"
       serverURL: "http://101.89.66.184:7054"
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org2.lenovo.com/users/Admin@org2.lenovo.com/tls/ca.crt"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org2.lenovo.com/users/Admin@org2.lenovo.com/tls/server.key"
         certfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org2.lenovo.com/users/Admin@org2.lenovo.com/tls/server.crt"
      peers:
       peer0:
        host: "peer0.org2.lenovo.com"
        #host: "101.89.63.227"
        port: 7051
        eventHost: "peer0.org2.lenovo.com"
        #eventHost: "101.89.63.227"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org2.lenovo.com/peers/peer0.org2.lenovo.com/tls/ca.crt"
         serverHostOverride: "peer0.org2.lenovo.com"
#       peer1:
#        host: "101.89.66.184"
#        port: 8051
#        eventHost: "101.89.66.184"
#        eventPort: 8053
#        primary: false
#        tls:
#         # Certificate location absolute path
#         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org2.lenovo.com/peers/peer1.org2.lenovo.com/msp/cacerts/ca.org2.lenovo.com-cert.pem"
#         serverHostOverride: "peer1.org2.lenovo.com"
   # Org3
    peerorg3:
      mspID: "Org3MSP"
      ca:
       tlsEnabled: false
       name: "ca-org3"
       serverURL: "http://218.245.66.177:7054"
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org3.lenovo.com/users/Admin@org3.lenovo.com/tls/ca.crt"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org3.lenovo.com/users/Admin@org3.lenovo.com/tls/server.key"
         certfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org3.lenovo.com/users/Admin@org3.lenovo.com/tls/server.crt"
      peers:
       peer0:
        #host: "101.89.63.168"
        host: "peer0.org3.lenovo.com"
        port: 7051
        #eventHost: "101.89.63.168"
        eventHost: "peer0.org3.lenovo.com"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org3.lenovo.com/peers/peer0.org3.lenovo.com/tls/ca.crt"
         serverHostOverride: "peer0.org3.lenovo.com"
 #      peer1:
 #       host: "218.245.66.177"
 #       port: 8051
 #       eventHost: "218.245.66.177"
 #       eventPort: 8053
 #       primary: false
 #       tls:
 #        # Certificate location absolute path
 #        certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org3.lenovo.com/peers/peer1.org3.lenovo.com/msp/cacerts/ca.org3.lenovo.com-cert.pem"
 #        serverHostOverride: "peer1.org3.lenovo.com"
   # Org4
    peerorg4:
      mspID: "Org4MSP"
      ca:
       tlsEnabled: false
       name: "ca-org4"
       serverURL: "http://218.245.66.178:7054"
       tls:
        # Comma-Separated list of paths
        certfiles : "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org4.lenovo.com/users/Admin@org4.lenovo.com/tls/ca.crt"
        client:
         keyfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org4.lenovo.com/users/Admin@org4.lenovo.com/tls/server.key"
         certfile: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org4.lenovo.com/users/Admin@org4.lenovo.com/tls/server.crt"
      peers:
       peer0:
        host: "peer0.org4.lenovo.com"
        #host: "101.89.63.161"
        port: 7051
        eventHost: "peer0.org4.lenovo.com"
        #eventHost: "101.89.63.161"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org4.lenovo.com/peers/peer0.org4.lenovo.com/tls/ca.crt"
         serverHostOverride: "peer0.org4.lenovo.com"
  #     peer1:
  #      host: "218.245.66.178"
  #      port: 8051
  #      eventHost: "218.245.66.178"
  #      eventPort: 8053
  #      primary: false
  #      tls:
  #       # Certificate location absolute path
  #       certificate: "$GOPATH/src/github.com/hyperledger/lenovo/networks/fixtures/blockchainkey/crypto-config/peerOrganizations/org4.lenovo.com/peers/peer1.org4.lenovo.com/msp/cacerts/ca.org4.lenovo.com-cert.pem"
  #       serverHostOverride: "peer1.org4.lenovo.com"
